### ISSUE TITLE
Error while launching from codespace

### ISSUE THREAD

**Issue by styphoiz** [second-state/ssvm-nodejs-starter#3]
I've tried checking the libstdc++ but still unable to get GLIBCXX_3.4.26 in

/usr/bin/node --inspect-brk=9286 app.js
Debugger listening on ws://127.0.0.1:9286/14f711e4-597f-4539-82fe-0444cf31345b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/workspace/ssvm-nodejs-starter/node_modules/ssvm/lib/binding/linux-x64/ssvm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/workspace/ssvm-nodejs-starter/node_modules/ssvm/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Waiting for the debugger to disconnect...
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/workspace/ssvm-nodejs-starter/node_modules/ssvm/lib/binding/linux-x64/ssvm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/workspace/ssvm-nodejs-starter/node_modules/ssvm/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by juntao** [comment]
Update the Dockerfile for codespaces. see c4dc6b5b28427d782fc9d6bed2a5894b086ed689 

Please try again and let me know if it works.

**Comment by styphoiz** [comment]
Thanks, it works.
