### ISSUE TITLE
No code changes can not run through?

### ISSUE THREAD

**Issue by dollarkillerx** [second-state/ssvm-nodejs-starter#5]
os： ubuntu18.0  x86
rustc 1.43.0 (4fb7144ed 2020-04-20)
```
wangy@mv-ubuntu-006:~/Github/RUST/ssvm-nodejs-starter$ ssvmup build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.01s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "Couldn\'t connect to server", code: 7, extra: None }', src/install/mod.rs:182:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Well, this is embarrassing.

ssvmup had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-03fda0f6-97e4-4a25-871f-86c7a5aaac2f.toml". Submit an issue or email with the subject of "ssvmup Crash Report" and include the report as an attachment.

- Authors: wangshishuo

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

```
name = 'ssvmup'
operating_system = 'unix:Ubuntu'
crate_version = '0.1.14'
explanation = '''
Panic occurred in file 'src/install/mod.rs' at line 182
'''
method = 'Panic'
backtrace = '''
   0:     0x563895865617 - backtrace::backtrace::trace::h1918625399014455
   1:     0x5638958639f5 - backtrace::capture::Backtrace::new::h1caa2b4438e7e3d1
   2:     0x5638957ba609 - human_panic::report::Report::new::h8373d669f137c710
   3:     0x5638957b9db3 - human_panic::handle_dump::h840eec528f13a739
   4:     0x56389551b1fc - ssvmup::setup_panic_hooks::{{closure}}::h41bcb094516de9f6
   5:     0x56389589721c - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:490
   6:     0x563895896dfb - rust_begin_unwind
                               at src/libstd/panicking.rs:388
   7:     0x5638958c00d1 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at src/libcore/panicking.rs:101
   8:     0x5638958bfed3 - core::option::expect_none_failed::h60849c4323f09783
                               at src/libcore/option.rs:1272
   9:     0x56389554a8a3 - ssvmup::install::download_prebuilt::h58bbb15c8877719a
  10:     0x563895548cff - ssvmup::install::download_prebuilt_or_cargo_install::h46501dde5634f700
  11:     0x56389555648c - ssvmup::command::build::Build::step_install_wasm_bindgen::h003d6ff043b675e7
  12:     0x563895554d0f - ssvmup::command::build::Build::run::he02babaf9bc75f04
  13:     0x563895523696 - ssvmup::command::run_ssvmup::h4a6426c2818fe4de
  14:     0x56389551ae85 - ssvmup::main::h745c576c2d1f7193
  15:     0x56389551bd23 - std::rt::lang_start::{{closure}}::h36a8e63f91640e1c
  16:     0x563895897688 - std::rt::lang_start_internal::{{closure}}::h6d21eebfa4beaf70
                               at src/libstd/rt.rs:52
                           std::panicking::try::do_call::h560a27b87db38b9c
                               at src/libstd/panicking.rs:297
                           std::panicking::try::h453d4afd696011f9
                               at src/libstd/panicking.rs:274
                           std::panic::catch_unwind::h211d02671f23030f
                               at src/libstd/panic.rs:394
                           std::rt::lang_start_internal::h464df2bbf46c7e7c
                               at src/libstd/rt.rs:51
  17:     0x56389551b2a2 - main
  18:     0x7f0d42293b97 - __libc_start_main
  19:     0x56389551565a - _start
  20:                0x0 - <unknown>
'''

```

**Comment by juntao** [comment]
The ssvmup tool requires an Internet connection to download the latest wasm-bindgen library it requires. It appears that you do not have an Internet connection.

**Comment by dollarkillerx** [comment]
Thank you should be the reason of the firewall
