### ISSUE TITLE
ssvmup build error

### ISSUE THREAD

**Issue by ulongx** [second-state/ssvm-nodejs-starter#8]
## error info
```
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "Couldn\'t connect to server", code: 7, extra: None }', src/install/mod.rs:182:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Well, this is embarrassing.

ssvmup had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-38176822-26b0-464a-b688-81828a90d116.toml". Submit an issue or email with the subject of "ssvmup Crash Report" and include the report as an attachment.

- Authors: wangshishuo

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```
##  report-84f344ff-48ef-4390-afc3-3d30f0f7102e.toml info：
```toml
"/tmp/report-84f344ff-48ef-4390-afc3-3d30f0f7102e.toml" 43L, 2495C                 1,1           All
name = 'ssvmup'
operating_system = 'unix:Ubuntu'
crate_version = '0.1.15'
explanation = '''
Panic occurred in file 'src/install/mod.rs' at line 182
'''
method = 'Panic'
backtrace = '''
   0:     0x55d6b1483b77 - backtrace::backtrace::trace::hfa6632c98169b3df
   1:     0x55d6b1482035 - backtrace::capture::Backtrace::new::h6549c5ab38a641f2
   2:     0x55d6b13d8bd9 - human_panic::report::Report::new::h38f5494317fd2945
   3:     0x55d6b13d8383 - human_panic::handle_dump::h0275ab777b783238
   4:     0x55d6b11392bc - ssvmup::setup_panic_hooks::{{closure}}::h35111d1bc1653272
   5:     0x55d6b14b585c - std::panicking::rust_panic_with_hook::h8dd35d3cd11497d7
                               at src/libstd/panicking.rs:490
   6:     0x55d6b14b543b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
   7:     0x55d6b14de711 - core::panicking::panic_fmt::hdf118db3fcd2d481
                               at src/libcore/panicking.rs:101
   8:     0x55d6b14de513 - core::option::expect_none_failed::h2982f0b1b6ba4b49
                               at src/libcore/option.rs:1272
   9:     0x55d6b1169168 - ssvmup::install::download_prebuilt::hfcf236b732371f41
  10:     0x55d6b116761f - ssvmup::install::download_prebuilt_or_cargo_install::h0e6b3aa2ef0ab5d5
  11:     0x55d6b1174c0c - ssvmup::command::build::Build::step_install_wasm_bindgen::h23079e71a00ce89f
  12:     0x55d6b117348f - ssvmup::command::build::Build::run::hebf401cb495b7a76
  13:     0x55d6b1141986 - ssvmup::command::run_ssvmup::h3b6eb04e11b9316e
  14:     0x55d6b1138f45 - ssvmup::main::h48876b40163d25d7
  15:     0x55d6b1139de3 - std::rt::lang_start::{{closure}}::ha243d93f29a11dd4
  16:     0x55d6b14b5cc8 - std::rt::lang_start_internal::{{closure}}::hfca5b90b4b1ebb0e
                               at src/libstd/rt.rs:52
                           std::panicking::try::do_call::hfc9c880ab92e6248
                               at src/libstd/panicking.rs:297
                           std::panicking::try::h2ed6f772c4dd6273
                               at src/libstd/panicking.rs:274
                           std::panic::catch_unwind::hc6028b0fc71765c5
                               at src/libstd/panic.rs:394
                           std::rt::lang_start_internal::heb6c9d57f3355ded
                               at src/libstd/rt.rs:51
  17:     0x55d6b1139362 - main
  18:     0x7f1e9dcf20b3 - __libc_start_main
  19:     0x55d6b113371a - _start
  20:                0x0 - <unknown>
```

**Comment by juntao** [comment]
You must have an Internet connection in order to run `ssvmup build`. It must fetch the latest `wasm_bindgen` binary files from a server. Thanks

**Comment by ulongx** [comment]
@juntao thank you! The network is okay, just can't update it. How to set .cargo config in Docker image.I suspect it is a problem with the cargo.io server URL
``` toml
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.52s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "Couldn\'t connect to server", code: 7, extra: None }', src/install/mod.rs:182:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Well, this is embarrassing.
```

**Comment by ulongx** [comment]
add this 199.232.4.133 raw.githubusercontent.com to hosts file，it can work...
